LIVE_SERVER_URL: 'ec2-13-228-71-31.ap-southeast-1.compute.amazonaws.com'
LIVE_SERVER_USER: 'rivai.sali'
LIVE_SERVER_PASSWORD: 'SEtan2013'

PRD_LIVE_SERVER_URL: 'ec2-13-228-71-31.ap-southeast-1.compute.amazonaws.com'
PRD_LIVE_SERVER_USER: 'rivai.sali'
PRD_LIVE_SERVER_PASSWORD: 'SEtan2013'

