DEV_LIVE_SERVER_URL: 'localhost'
DEV_LIVE_SERVER_USER: 'suhanlee'
DEV_LIVE_SERVER_PASSWORD: 'game1234'


#LIVE_SERVER_URL: '192.168.0.6'
#LIVE_SERVER_USER: 'suhanlee'
#LIVE_SERVER_PASSWORD: 'game1234'


LIVE_SERVER_URL: 'https://api.cloud.wowza.com'
LIVE_SERVER_USER: 'wowza'
LIVE_SERVER_PASSWORD: 'i-827fbd24'

PRD_LIVE_SERVER_URL: 'https://api.cloud.wowza.com'
PRD_LIVE_SERVER_USER: 'wowza'
PRD_LIVE_SERVER_PASSWORD: 'i-827fbd24'

